terraform-ibm-modules/terraform-ibm-powervs-workspace

README.md, examples/basic/main.tf, tests/pr_test.go, version.tf
second commit fixes test names and tf constraints
```
/run pipeline
```
=> chore: second commit fixes test names and tf constraints

README.md, cra-config.yaml, examples/basic/main.tf, examples/basic/variables.tf, tests/pr_test.go
Create a first release
```
/run pipeline
```
=> feat: docs link and test enable main example

modules/pi-workspace/README.md
update source usage in readme for module usage
```
/run pipeline
```
=> docs: update source usage

modules/pi-workspace/pi_images.tf
This fix identifies the missing image if not available correctly by checking on the data source directly.
```
/run pipeline
```
=> fix: image import from data source lookup

examples/basic/provider.tf, main.tf, variables.tf
Enable new PER DCs, WDC06 and MAD02 
- [] Patch release (`x.x.X`)
```
/run pipeline
```
=> feat: enable wdc06 and mad02 PER DCs

examples/basic/README.md, examples/basic/version.tf, modules/pi-workspace/pi_subnets.tf
pi_network_jumbo depreciated. using pi_network_mtu
```
/run pipeline
```
=> fix: pi_network_jumbo depreciated. using pi_network_mtu

main.tf
add frankfurt 02 to PER DC list
```
/run pipeline
```
=> feat: add frankfurt 02 to PER DC list

README.md, examples/basic/provider.tf, examples/basic/variables.tf, main.tf, variables.tf
support wdc07, mad04, sao04 eu-de-2 per enabled DC
```
/run pipeline
```
=> feat: support wdc07, mad04, sao04 eu-de-2 per enabled DC

main.tf
switch eu-de-1 to PER category
```
/run pipeline
```
=> feat: switch eu-de-1 to PER

tests/common-go-assets/cloudinfo-region-power-prefs.yaml, tests/pr_test.go
add regions prefs.yaml file and maintain it in this repo
```
/run pipeline
```
=> ci: add regions prefs.yaml file

.secrets.baseline, README.md, main.tf, modules/pi-workspace/README.md, modules/pi-workspace/pi_subnets.tf, modules/pi-workspace/versions.tf
Adding PER support for PowerVS location dal12.
```
/run pipeline
```
=> feat: PER support for dal12

main.tf
switch sao01 to PER DC
```
/run pipeline
```
=> feat: switch sao01 to PER DC

README.md, examples/basic/README.md
=> docs: update description

main.tf
Enabled PER for DC location tok04
```
/run pipeline
```
=> feat: enable PER for tok04 DC

main.tf
Switch osa21 to PER DC
```
/run pipeline
```
=> feat: switch osa21 to PER DC

main.tf
switch lon06 to PER DC
```
/run pipeline
```
=> feat: switch lon06 to PER DC

main.tf
switch tor01 and us-south DC to PER DC
```
/run pipeline
```
=> feat: switch tor01 and us-south DC to PER DC

.secrets.baseline, README.md, variables.tf
=> fix: make sap type optional and update readme

.secrets.baseline, README.md, examples/basic/README.md, examples/basic/version.tf, version.tf
=> feat: upgrade minimum tf version to 1.9.0 

examples/basic/README.md, examples/basic/version.tf
=> chore: upgrade tf provider

README.md, examples/basic/README.md, examples/basic/version.tf, pi_images.tf, pi_networks.tf, version.tf
Features:
1. Support tags for networks and images
2. Upgrade minimum IBM provider version to >=1.71.0
```
/run pipeline
```
=> feat: support tags for network, images

tests/common-go-assets/cloudinfo-region-power-prefs.yaml, tests/pr_test.go
=> chore: updated terratest

.secrets.baseline, README.md, examples/basic/README.md, examples/basic/main.tf, examples/basic/variables.tf, examples/basic/version.tf, pi_images.tf, tests/go.mod, tests/go.sum, variables.tf
SKIP UPGRADE TEST: Breaking change remove stock image import
```
/run pipeline
```
=> feat: remove stock images import

pi_images.tf
=> fix: attribute vendor for image output

examples/basic/README.md, examples/basic/version.tf
SKIP UPGRADE TEST: network retry
```
/run pipeline
```
=> chore: upgrade tf provider version
